version: '3.8'

services:
  app:
    build: .
    ports:
      - "8888:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine3.17
    volumes:
      - $HOME/postgresql/currencies:/var/lib/postgresql/data/
    env_file:
      - .env

  cache:
    image: redis:latest

  worker:
    build:
      context: .

    entrypoint: celery
    command: -A config.celery.app worker --loglevel=info
    volumes:
      - .:/src
    links:
      - cache
    depends_on:
      - cache
    env_file:
      - .env

  beat:
    build:
      context: .
    entrypoint: celery
    command: -A config.celery.app beat --loglevel=info
    volumes:
      - .:/src
    links:
      - worker
      - cache
    depends_on:
      - worker
      - cache
    env_file:
      - .env

  flower:
    build:
      context: .
    entrypoint: celery
    command: -A config.celery.app flower
    volumes:
      - ./src:/src
    links:
      - cache
    depends_on:
      - cache
    ports:
      - "5555:5555"
    env_file:
      - .env
