# Generated by Django 4.2.5 on 2023-10-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_code', models.CharField(max_length=3, verbose_name='код валюты')),
                ('date', models.DateField(verbose_name='дата')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='курс')),
            ],
            options={
                'verbose_name': 'курс валют',
                'verbose_name_plural': 'курсы валют',
                'ordering': ('-date',),
            },
        ),
    ]
