# Generated by Django 4.2.5 on 2023-10-05 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='порог')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.rate', verbose_name='курс валюты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отслеживаемая валюта',
                'verbose_name_plural': 'отслеживаемые валюты',
                'ordering': ('id',),
            },
        ),
    ]
