# Generated by Django 4.2.5 on 2023-10-06 11:55

from django.db import migrations, models
import django.db.models.deletion


def set_currency(apps, schema_editor):
    Rate = apps.get_model('rates', 'Rate')
    Currency = apps.get_model('rates', 'Currency')
    to_create = list()
    rate_objects = Rate.objects.distinct('char_code').order_by('char_code')
    for entry in rate_objects:
        to_create.append(Currency(char_code=entry.char_code))
    Currency.objects.bulk_create(to_create)

    for currency in Currency.objects.all():
        Rate.objects.filter(char_code=currency.char_code).update(currency_id=currency.id)


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_usercurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_code', models.CharField(max_length=3, verbose_name='код валюты')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюты',
                'ordering': ('char_code',),
            },
        ),
        migrations.AddField(
            model_name='rate',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.currency', verbose_name='валюта'),
        ),
        migrations.RunPython(set_currency, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='rate',
            name='char_code',
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.currency', verbose_name='курс валюты'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.currency', verbose_name='валюта'),
        ),
    ]
